# Generated by Django 4.1.2 on 2023-07-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School_Academy', '0002_remove_profile_bio_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
